targets:
  $default:
    builders:
      json_serializable|json_serializable:
        generate_for:
          - "lib/src/models/**.dart"
      freezed|freezed:
        generate_for:
          - "lib/src/errors/**.dart"
          - "lib/src/models/**.dart"
